---
title: "projeto-integrado-fase-01-rm351578"
author: "Rodrigo"
date: "2024-02-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(summarytools)
library(gmodels)
library(dplyr)
```


```{r}

# Quadro Conceitual Estatístico - Resposta


```



```{r }

# Leitura da Base
 
#Carregando a base de dados
Base_ScoreCredito <- read.csv("Base_ScoreCredito_QuantumFinance.csv", row.names=1, sep=";", stringsAsFactors=TRUE)



# avaliando o nome e o formato das variáveis
str(Base_ScoreCredito)


```

```{r}
#Verificando os quartis das variaveis
summary(Base_ScoreCredito)

```

```{r}

#histograma de dados quantitativos

attach(Base_ScoreCredito)

par (mfrow=c(3,2))

hist(idade)
hist(Qte_dependentes)
hist(tempo_ultimoservico)
hist(trabalha)
hist(reg_moradia)
hist(casa_propria)
hist(reg_moradia)
hist(vl_imovel_em_mil)
hist(Qte_cartoes)
hist(Qte_carros)
par (mfrow=c(1,1))


``` 

```{r}
#box plot de dados quantitativos

par (mfrow=c(1,2))

boxplot(Base_ScoreCredito$idade, main="idade", range=3)
boxplot(Base_ScoreCredito$Qte_dependentes, main="Qte_Dependentes", range=3)
boxplot(Base_ScoreCredito$tempo_ultimoservico, main="tempo_ultimoservico", range=3)
boxplot(Base_ScoreCredito$reg_moradia, main="reg_moradia", range=3)
boxplot(Base_ScoreCredito$casa_propria, main="casa_propria", range=3)
boxplot(Base_ScoreCredito$vl_imovel_em_mil, main="vl_imovel_em_mil", range=3)
boxplot(Base_ScoreCredito$vl_salario_mil, main="vl_salario_mil", range=3)
boxplot(Base_ScoreCredito$Qte_cartoes, main="Qte_cartoes", range=3)
boxplot(Base_ScoreCredito$Qte_carros, main="Qte_carros", range=3)
par (mfrow=c(1,1))

```

```{r}

#selecionando variaveis quantiativas para correlação

score_quant <- subset(Base_ScoreCredito, select=c(idade,	Qte_dependentes,	tempo_ultimoservico,	vl_salario_mil,                                                vl_imovel_em_mil,	Qte_cartoes,	Qte_carros) )
```


```{r}
#verificando o tipo das variaves e transformando para numerico para assim possibilitar a verificacao da correlacao entre elas

summary(score_quant)

tipos_colunas <- sapply(score_quant, class)

print(tipos_colunas)

score_quant$vl_salario_mil <- as.numeric(score_quant$vl_salario_mil)

tipos_colunas <- sapply(score_quant, class)

print(tipos_colunas)

summary(score_quant)

```

```{r}

#gerando matriz de correlação

correlacao <- cor(score_quant)

mc <- correlacao

print(mc, digits = 2)
```

```{r}

#print do gráfico de correlação

library(corrplot)

corrplot(mc, method="number", type="upper")

#apenas a variavel tempo de serviço e idade possuem uma correlação forte
```

```{r}
library(Hmisc)
mcorr = rcorr(as.matrix(score_quant));mcorr
mcorr$r # correlacao
mcorr$P # p-valor
mcorr$n # numero de observacoes

library(PerformanceAnalytics)

chart.Correlation(score_quant,histogram=TRUE)
```

```{r}
score_quali <- subset(Base_ScoreCredito, select =c(sexo, estado_civil, escola, trabalha, reg_moradia, casa_propria))
```

```{r}

scoredf1 <- Base_ScoreCredito

scoredf1$SCORE_CREDITO <- as.numeric(gsub(",",".",Base_ScoreCredito$SCORE_CREDITO))
scoredf1$vl_salario_mil <- as.numeric(gsub(",",".",Base_ScoreCredito$vl_salario_mil))

hist(scoredf1$SCORE_CREDITO)

score_quant2 <- subset(scoredf1, select=c(idade,	Qte_dependentes,	tempo_ultimoservico,	vl_salario_mil, vl_imovel_em_mil,	Qte_cartoes,	Qte_carros, SCORE_CREDITO) )
correlacao2 <- cor(score_quant2)

mc2 <- correlacao2

corrplot(mc2, method="number", type="upper")


```



```{r}
library(dplyr)

# transformando a variavel score em uma variavel qualitativa

quantile(scoredf1$SCORE_CREDITO, seq(0, 1, 0.25))

scoredf1$fx_score_num <- ntile(scoredf1$SCORE_CREDITO, 4)

scoredf1$fx_score_quali <- factor(scoredf1$fx_score_num, levels=c(1,2,3,4),labels = c(labels=c("[162 a 375]",                                               "(375 a 449.6]","(449.6 a 540.9]", "(540.9 a 979.6]")))

scoredf1$fx_score_quali <- factor(scoredf1$fx_score_quali, ordered =TRUE)

###########
quantile(scoredf1$vl_salario_mil, seq(0, 1, 0.20))

scoredf1$fx_vl_salario_em_mil_num <- ntile(Base_ScoreCredito$vl_salario_mil, 5)

scoredf1$fx_vl_salario_em_mil_quali <- factor(scoredf1$fx_vl_salario_em_mil_num, levels=c(1,2,3,4,5),labels = c(labels=c("[0 a 19]",                                               "(19 a 26]","(26 a 79]", "(79 a 122]","(122 a 233]")))

scoredf1$fx_vl_salario_em_mil_quali <- factor(scoredf1$fx_vl_salario_em_mil_quali, ordered =TRUE)

###########

quantile(scoredf1$tempo_ultimoservico, seq(0, 1, 0.25))

scoredf1$fx_tempo_ultimoservico_num <- ntile(Base_ScoreCredito$tempo_ultimoservico, 4)

scoredf1$fx_tempo_ultimoservico_quali <- factor(scoredf1$fx_tempo_ultimoservico_num, levels=c(1,2,3,4),labels = c(labels=c("[7 a 30]", "(30 a 34]","(34 a 39]", "(39 a 57]")))

scoredf1$fx_tempo_ultimoservico_quali <- factor(scoredf1$fx_tempo_ultimoservico_quali, ordered =TRUE)

###########

quantile(scoredf1$idade, seq(0, 1, 0.20))

scoredf1$fx_idade_num <- ntile(Base_ScoreCredito$idade, 5)

scoredf1$fx_idade_quali <- factor(scoredf1$fx_idade_num, levels=c(1,2,3,4,5),labels = c(labels=c("[26 a 39]", "(39 a 44]","(44 a 48]", "(48 a 53]","(53 a 73]")))

scoredf1$fx_idade_quali <- factor(scoredf1$fx_idade_quali, ordered =TRUE)
```
```{r}
str(scoredf1)
```

```{r}
library(gmodels)
CrossTable(scoredf1$fx_score_quali,scoredf1$fx_idade_quali, prop.r = FALSE, prop.c = FALSE, prop.t = FALSE,
           expected = TRUE, prop.chisq = FALSE, chisq = FALSE)
```

```{r}
CrossTable(scoredf1$fx_score_quali,scoredf1$fx_vl_salario_em_mil_quali, prop.r = FALSE, prop.c = FALSE, prop.t = FALSE,
           expected = TRUE, prop.chisq = FALSE, chisq = FALSE)
```

```{r}
CrossTable(scoredf1$fx_score_quali,scoredf1$fx_tempo_ultimoservico_quali, prop.r = FALSE, prop.c = FALSE, prop.t = FALSE,
           expected = TRUE, prop.chisq = FALSE, chisq = FALSE)
```

```{r}
CrossTable(scoredf1$fx_score_quali,scoredf1$sexo, prop.r = FALSE, prop.c = FALSE, prop.t = FALSE,
           expected = TRUE, prop.chisq = FALSE, chisq = FALSE)
```

```{r}
CrossTable(scoredf1$fx_score_quali,scoredf1$reg_moradia, prop.r = FALSE, prop.c = FALSE, prop.t = FALSE,
           expected = TRUE, prop.chisq = FALSE, chisq = FALSE)
```

```{r}
CrossTable(scoredf1$fx_score_quali,scoredf1$trabalha, prop.r = FALSE, prop.c = FALSE, prop.t = FALSE,
           expected = TRUE, prop.chisq = FALSE, chisq = FALSE)
```

```{r}
CrossTable(scoredf1$fx_score_quali,scoredf1$escola, prop.r = FALSE, prop.c = FALSE, prop.t = FALSE,
           expected = TRUE, prop.chisq = FALSE, chisq = FALSE)
```