---
title: "Importar Series Temporais"
author: "Adelaide Alves"
date: "Fevereiro de 2024"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```


```{r}

#pacotes de series temporais
install.packages("forecast")
install.packages("ggplot2")
install.packages("lmtest")
install.packages("seasonal")
install.packages("seasonalview")

library(ggplot2)
library(forecast)
library(seasonal)
library(seasonalview)

```

```{r faturamento}
# importar a serie temporal

Faturamento <- read.csv("Faturamento.csv", sep=";", stringsAsFactors=TRUE)

summary(Faturamento)


Faturamento$tempo <- as.numeric(row.names(Faturamento))

summary(Faturamento)

reg_fat <- lm(Faturamento~tempo, data=Faturamento)

summary(reg_fat)
``` 

```{r }
 

#formatar a serie temporal e informar o periodo de tempo (frequency)
serie_fat = ts(Faturamento[3],start=c(2011,1), end=c(2013,12), frequency=12)
length(serie_fat)
print(serie_fat)



# grafico da serie temporal
autoplot(serie_fat)

```

```{r energia}
#b) Consumo_Energia_Agricultura.csv

# importar a serie temporal

Consumo_Energia_Agricultura <- read.csv("Consumo_Energia_Agricultura.csv", sep=";", stringsAsFactors=TRUE)

summary(Consumo_Energia_Agricultura)



Consumo_Energia_Agricultura$tempo <- as.numeric(row.names(Consumo_Energia_Agricultura))

summary(Consumo_Energia_Agricultura)

reg_energia <- lm(Consumo_energia_Agricultura~tempo, data=Consumo_Energia_Agricultura)

summary(reg_energia)



``` 

```{r }
 
#formatar a serie temporal e informar o periodo de tempo (frequency)
serie_energia = ts(Consumo_Energia_Agricultura[3],start=c(2007,1), end=c(2008,12), frequency=12)
length(serie_energia)
print(serie_energia)

# formato do dado eh uma serie temporal
class(serie_energia)

# grafico da serie temporal
autoplot(serie_energia)




```


```{r bike}
#c) Bike_Sharing_day.csv

Bike_Sharing_day <- read.csv("Bike_Sharing_day.csv")


# Excluir a data 2012-02-29 correspondente a linha 425 
Bike_Sharing_day<-Bike_Sharing_day[(-425),] 

serie_Bike = ts(Bike_Sharing_day[16],start=2011, frequency=365)
length(serie_Bike)
# print(serie_Bike)


# formato do dado de uma serie temporal
class(serie_Bike)


# grafico da serie temporal
autoplot(serie_Bike)
```

